
// This file has been generated by the GUI designer. Do not modify.
namespace ChatbotFrontend
{
	public partial class RateWindow
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview3;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.VBox vbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Button submit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatbotFrontend.RateWindow
			this.Name = "ChatbotFrontend.RateWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("RateWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ChatbotFrontend.RateWindow.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.Buffer.Text = global::Mono.Unix.Catalog.GetString("Rate del\nUsuario");
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add(this.textview3);
			this.vbox3.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow1]));
			w2.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("0"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 0;
			this.vbox3.Add(this.combobox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.combobox3]));
			w3.Position = 1;
			w3.Fill = false;
			this.hbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.Buffer.Text = global::Mono.Unix.Catalog.GetString("Rate del \nChatbot");
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w6.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("0"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.vbox1.Add(this.combobox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.combobox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.submit = new global::Gtk.Button();
			this.submit.CanFocus = true;
			this.submit.Name = "submit";
			this.submit.UseUnderline = true;
			this.submit.Label = global::Mono.Unix.Catalog.GetString("Submit");
			this.vbox1.Add(this.submit);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.submit]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox2.Add(this.vbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.Add(this.hbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 143;
			this.DefaultHeight = 177;
			this.Show();
			this.submit.Clicked += new global::System.EventHandler(this.OnSubmitClicked);
		}
	}
}
