
// This file has been generated by the GUI designer. Do not modify.
namespace ChatbotFrontend
{
	public partial class MainWindow
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview3;

		private global::Gtk.Button SendButton;

		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button beginDialog;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView seedview;

		private global::Gtk.Button saveLog;

		private global::Gtk.Button button7;

		private global::Gtk.Button endDialog;

		private global::Gtk.Button ClearChat;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatbotFrontend.MainWindow
			this.Name = "ChatbotFrontend.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Chatbot");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 700;
			this.DefaultHeight = 500;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child ChatbotFrontend.MainWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.textview1.RightMargin = 1;
			this.vbox1.Add(this.textview1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.textview1]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add(this.textview3);
			this.hbox5.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.GtkScrolledWindow1]));
			w3.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.SendButton = new global::Gtk.Button();
			this.SendButton.CanFocus = true;
			this.SendButton.Name = "SendButton";
			this.SendButton.UseUnderline = true;
			this.SendButton.Label = global::Mono.Unix.Catalog.GetString("Enviar");
			this.hbox5.Add(this.SendButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.SendButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.beginDialog = new global::Gtk.Button();
			this.beginDialog.CanFocus = true;
			this.beginDialog.Name = "beginDialog";
			this.beginDialog.UseUnderline = true;
			this.beginDialog.Label = global::Mono.Unix.Catalog.GetString("Iniciar Chat");
			this.hbox3.Add(this.beginDialog);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.beginDialog]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.seedview = new global::Gtk.TextView();
			this.seedview.Buffer.Text = global::Mono.Unix.Catalog.GetString("Seed");
			this.seedview.CanFocus = true;
			this.seedview.Name = "seedview";
			this.seedview.Overwrite = true;
			this.seedview.RightMargin = 15;
			this.GtkScrolledWindow.Add(this.seedview);
			this.hbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow]));
			w9.Position = 1;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.saveLog = new global::Gtk.Button();
			this.saveLog.CanFocus = true;
			this.saveLog.Name = "saveLog";
			this.saveLog.UseUnderline = true;
			this.saveLog.Label = global::Mono.Unix.Catalog.GetString("Guardar Log");
			this.vbox3.Add(this.saveLog);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.saveLog]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString("Cargar Log");
			this.vbox3.Add(this.button7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button7]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.endDialog = new global::Gtk.Button();
			this.endDialog.CanFocus = true;
			this.endDialog.Name = "endDialog";
			this.endDialog.UseUnderline = true;
			this.endDialog.Label = global::Mono.Unix.Catalog.GetString("Terminar Chat");
			this.vbox3.Add(this.endDialog);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.endDialog]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ClearChat = new global::Gtk.Button();
			this.ClearChat.CanFocus = true;
			this.ClearChat.Name = "ClearChat";
			this.ClearChat.UseUnderline = true;
			this.ClearChat.Label = global::Mono.Unix.Catalog.GetString("Limpiar Pantalla");
			this.vbox3.Add(this.ClearChat);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.ClearChat]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.SendButton.Clicked += new global::System.EventHandler(this.OnSendButtonClicked);
			this.beginDialog.Clicked += new global::System.EventHandler(this.clickedBegin);
			this.saveLog.Clicked += new global::System.EventHandler(this.OnSaveLogClicked);
			this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
			this.endDialog.Clicked += new global::System.EventHandler(this.OnEndDialogClicked);
			this.ClearChat.Clicked += new global::System.EventHandler(this.OnClearChatClicked);
		}
	}
}
