
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.TextView textview1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview3;

	private global::Gtk.Button SendButton;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Button BeginButton;

	private global::Gtk.Button button5;

	private global::Gtk.Button button7;

	private global::Gtk.Button button9;

	private global::Gtk.Button button11;

	private global::Gtk.Button ClearChat;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Chatbot");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.vbox1.Add(this.textview1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.textview1]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow1.Add(this.textview3);
		this.hbox5.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.GtkScrolledWindow1]));
		w3.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.SendButton = new global::Gtk.Button();
		this.SendButton.CanFocus = true;
		this.SendButton.Name = "SendButton";
		this.SendButton.UseUnderline = true;
		this.SendButton.Label = global::Mono.Unix.Catalog.GetString("Enviar");
		this.hbox5.Add(this.SendButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.SendButton]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.BeginButton = new global::Gtk.Button();
		this.BeginButton.CanFocus = true;
		this.BeginButton.Name = "BeginButton";
		this.BeginButton.UseUnderline = true;
		this.BeginButton.Label = global::Mono.Unix.Catalog.GetString("Iniciar Chat");
		this.vbox3.Add(this.BeginButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.BeginButton]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Guardar Log");
		this.vbox3.Add(this.button5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button5]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Cargar Log");
		this.vbox3.Add(this.button7);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button7]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Rate Chat");
		this.vbox3.Add(this.button9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button9]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Terminar Chat");
		this.vbox3.Add(this.button11);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button11]));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.ClearChat = new global::Gtk.Button();
		this.ClearChat.CanFocus = true;
		this.ClearChat.Name = "ClearChat";
		this.ClearChat.UseUnderline = true;
		this.ClearChat.Label = global::Mono.Unix.Catalog.GetString("Limpiar Pantalla");
		this.vbox3.Add(this.ClearChat);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.ClearChat]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 5;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SendButton.Clicked += new global::System.EventHandler(this.OnSendButtonClicked);
		this.BeginButton.Clicked += new global::System.EventHandler(this.OnBeginButtonClicked);
		this.ClearChat.Clicked += new global::System.EventHandler(this.OnClearChatClicked);
	}
}
